### ISSUE TITLE
Problem: dataset with 37,000 files fails at index AIP stage

### ISSUE THREAD

**Issue by mjaddis** [JiscRDSS/rdss-archivematica#106]
york_small_files2 is a test of 37,000 files from York that we have been running through our QA env.   It failed at the very end of the process at the index AIP stage.  After 10180 seconds of processing, the 'index AIP' task failed with exit code -9 and no error details reported in the Dashboard. 

```
SIP UUID: e2c3290a-02b0-4e0c-9f34-9a8c6a8f66ca
AIP info: [{u'status': u'UPLOADED', u'current_path': u'e2c3/290a/02b0/4e0c/9f34/9a8c/6a8f/66ca/york_small_files_2-e2c3290a-02b0-4e0c-9f34-9a8c6a8f66ca.7z', u'origin_pipeline': u'/api/v2/pipeline/5e8890c1-6b1a-457d-92a8-280ddb54fb97/', u'uuid': u'e2c3290a-02b0-4e0c-9f34-9a8c6a8f66ca', u'package_type': u'AIP', u'misc_attributes': {}, u'current_full_path': u'/var/archivematica/sharedDirectory/www/AIPsStore/e2c3/290a/02b0/4e0c/9f34/9a8c/6a8f/66ca/york_small_files_2-e2c3290a-02b0-4e0c-9f34-9a8c6a8f66ca.7z', u'current_location': u'/api/v2/location/1e5ec755-6a00-4d98-b35d-993b19fd4ef8/', u'related_packages': [], u'size': 698402199, u'resource_uri': u'/api/v2/file/e2c3290a-02b0-4e0c-9f34-9a8c6a8f66ca/'}]
Indexing additional identifiers %s []
Indexing AIP info
```

The preceding task to store the AIP reports in the Dashboard as completing OK, but the stdout suggest there may be a problem with this, which perhaps explains why the index task then failed.

```
Storage service created SIP: {u'error_message': u'xmlSAX2Characters: huge text node, line 69663, column 125 (line 69663)', u'traceback': u'Traceback (most recent call last):\n\n  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 220, in wrapper\n    response = callback(request, *args, **kwargs)\n\n  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 451, in dispatch_list\n    return self.dispatch(\'list\', request, **kwargs)\n\n  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 483, in dispatch\n    response = method(request, **kwargs)\n\n  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 1380, in post_list\n    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))\n\n  File "/src/storage_service/locations/api/resources.py", line 531, in obj_create\n    bundle.obj.store_aip(origin_location, origin_path, related_package_uuid)\n\n  File "/src/storage_service/locations/models/package.py", line 461, in store_aip\n    root = etree.parse(pointer_absolute_path)\n\n  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:81117)\n\n  File "src/lxml/parser.pxi", line 1811, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:117848)\n\n  File "src/lxml/parser.pxi", line 1837, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:118195)\n\n  File "src/lxml/parser.pxi", line 1741, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:117107)\n\n  File "src/lxml/parser.pxi", line 1138, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:111653)\n\n  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105109)\n\n  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106817)\n\n  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105671)\n\nXMLSyntaxError: xmlSAX2Characters: huge text node, line 69663, column 125 (line 69663)\n'}
```

The above are from the Dashboard.  I haven't looked at the log files.

Note that the AIP contains 77,000 files (original files, normalised files, thumbnails) and the METS is just short of 1GB in size.   Therefore, the METS file is a bit of a beast for processing.

Assigning to Justin for triage who can then decide who should investigate further.

**Comment by mamedin** [comment]
This is the error line in the mcp server log:

```
ubuntu@qa-aws-rdss-archivematica:~/rdss-archivematica/compose$ docker-compose logs --tail 2000 archivematica-mcp-server 2>&1 | grep -A3 -B3 xmlSAX2Characters
archivematica-mcp-server_1                      | INFO      2017-11-04 11:13:18  archivematica.mcp.server:jobChainLink:__init__:91:  Running Store the AIP (unit e2c3290a-02b0-4e0c-9f34-9a8c6a8f66ca)
archivematica-mcp-server_1                      | INFO      2017-11-04 11:13:18  archivematica.mcp.server:taskStandard:performTask:74:  Executing storeAIP_v0.0 {'arguments': '"/api/v2/location/1e5ec755-6a00-4d98-b35d-993b19fd4ef8/" "/var/archivematica/sharedDirectory/currentlyProcessing/york_small_files_2-e2c3290a-02b0-4e0c-9f34-9a8c6a8f66ca/york_small_files_2-e2c3290a-02b0-4e0c-9f34-9a8c6a8f66ca.7z" "e2c3290a-02b0-4e0c-9f34-9a8c6a8f66ca" "york_small_files_2" "SIP"', 'createdDate': '2017-11-04 11:13:18.213368+00:00'}
archivematica-mcp-server_1                      | DEBUG     2017-11-04 11:13:18  archivematica.mcp.server:taskStandard:performTask:93:  Finished performing task 8399bc8d-5f91-4317-be98-51bf5d668738
archivematica-mcp-server_1                      | DEBUG     2017-11-04 11:14:01  archivematica.mcp.server:taskStandard:check_request_status:98:  Task e9e15a7e-cd60-4ee7-907d-9360ddd2bd5f finished! Result COMPLETE - {'stdOut': 'Storage service created SIP: {u\'error_message\': u\'xmlSAX2Characters: huge text node, line 69663, column 125 (line 69663)\', u\'traceback\': u\'Traceback (most recent call last):\\n\\n  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 220, in wrapper\\n    response = callback(request, *args, **kwargs)\\n\\n  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 451, in dispatch_list\\n    return self.dispatch(\\\'list\\\', request, **kwargs)\\n\\n  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 483, in dispatch\\n    response = method(request, **kwargs)\\n\\n  File "/usr/local/lib/python2.7/site-packages/tastypie/resources.py", line 1380, in post_list\\n    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))\\n\\n  File "/src/storage_service/locations/api/resources.py", line 531, in obj_create\\n    bundle.obj.store_aip(origin_location, origin_path, related_package_uuid)\\n\\n  File "/src/storage_service/locations/models/package.py", line 461, in store_aip\\n    root = etree.parse(pointer_absolute_path)\\n\\n  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:81117)\\n\\n  File "src/lxml/parser.pxi", line 1811, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:117848)\\n\\n  File "src/lxml/parser.pxi", line 1837, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:118195)\\n\\n  File "src/lxml/parser.pxi", line 1741, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:117107)\\n\\n  File "src/lxml/parser.pxi", line 1138, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:111653)\\n\\n  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105109)\\n\\n  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106817)\\n\\n  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105671)\\n\\nXMLSyntaxError: xmlSAX2Characters: huge text node, line 69663, column 125 (line 69663)\\n\'}\n', 'exitCode': 0, 'stdError': "storeAIP.py: INFO      2017-11-04 11:13:18,923  archivematica.common:create_file:267:  Creating file with {'size': 698402199, 'package_type': 'AIP', 'current_path': 'york_small_files_2-e2c3290a-02b0-4e0c-9f34-9a8c6a8f66ca.7z', 'origin_pipeline': u'/api/v2/pipeline/5e8890c1-6b1a-457d-92a8-280ddb54fb97/', 'uuid': 'e2c3290a-02b0-4e0c-9f34-9a8c6a8f66ca', 'related_package_uuid': None, 'current_location': '/api/v2/location/1e5ec755-6a00-4d98-b35d-993b19fd4ef8/', 'origin_path': u'currentlyProcessing/york_small_files_2-e2c3290a-02b0-4e0c-9f34-9a8c6a8f66ca/york_small_files_2-e2c3290a-02b0-4e0c-9f34-9a8c6a8f66ca.7z', 'origin_location': u'/api/v2/location/4bda73bc-1f67-42e0-a49a-54fc5a6d6c20/'}\n"}
archivematica-mcp-server_1                      | Logging task output to db e9e15a7e-cd60-4ee7-907d-9360ddd2bd5f
archivematica-mcp-server_1                      | INFO      2017-11-04 11:14:01  archivematica.mcp.server:jobChainLink:__init__:91:  Running Index AIP (unit e2c3290a-02b0-4e0c-9f34-9a8c6a8f66ca)
archivematica-mcp-server_1                      | INFO      2017-11-04 11:14:01  archivematica.mcp.server:taskStandard:performTask:74:  Executing indexAIP_v0.0 {'arguments': '"e2c3290a-02b0-4e0c-9f34-9a8c6a8f66ca" "york_small_files_2" "/var/archivematica/sharedDirectory/currentlyProcessing/york_small_files_2-e2c3290a-02b0-4e0c-9f34-9a8c6a8f66ca/" "SIP"', 'createdDate': '2017-11-04 11:14:01.075875+00:00'}
```

**Comment by jhsimpson** [comment]
This is caused by jiscRDSS/archivematica#39. This should be retested after that issue is resolved and the rdss-archivematica repo has been updated to include the fix.
