### ISSUE TITLE
Problem: Large dataset (20 GB) fail at index AIP Stage

### ISSUE THREAD

**Issue by mamedin** [JiscRDSS/rdss-archivematica#109]
Taking a look to #106, the ES container log shows that  10.1021 dataset (>20GB) failed at the index AIP Stage.

Both issues match the same job but they seem to be different problems.

( https://archivematica.jisc-qa.archivematica.org/tasks/31872d5c-bcd4-46ae-8ddd-9e8aa97c76e3/ )

Dashboard log:
```

indexAIP.py: WARNING   2017-10-25 09:31:10,576  elasticsearch:log_request_fail:82:  POST http://elasticsearch:9200/aips/aip [status:N/A request:1.474s]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 78, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 840, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
```
Elasticsearch container log:

```
elasticsearch_1                                 | [2017-10-25 09:34:26,737][WARN ][http.netty               ] [TestNode] Caught exception while handling client http traffic, closing connection [id: 0x06b95204, /172.18.0.16:33068 => /172.18.0.4:9200]
elasticsearch_1                                 | org.elasticsearch.common.netty.handler.codec.frame.TooLongFrameException: HTTP content length exceeded 104857600 bytes.
```

**Comment by jhsimpson** [comment]
This bit `HTTP content length exceeded 104857600 bytes` is the problem.

The Index AIP Microservice is taking the METS from the AIP and converting it into a json document and then inserting that into the Elasticsearch index.  The json being produced is larger than 104 mb.

JiscRDSS/archivematica#39 is related here.  That issue when resolved will reduce the size of the pointer file.  I created JiscRDSS/archivematica#41 to address the same need for AIP METS files.

**Comment by mamedin** [comment]
Fixed: https://github.com/JiscRDSS/archivematica/pull/42

**Comment by mamedin** [comment]
The https://github.com/JiscRDSS/archivematica/pull/42 was not merget yet. I'm reopening the issue.
