### ISSUE TITLE
Problem: Clamav fails for file with diacritic in filename

### ISSUE THREAD

**Issue by mjaddis** [JiscRDSS/rdss-archivematica#57]
QA env. 10.1017 dataset.  virus scanning fails and reports the message below in the Dashboard.  I'm guessing this is a problem with the acute accent above the e in the filename but haven't looked at the code to confirm.

"d9db1913-a8ab-4776-86ec-b7ce2b7cda79" "/var/archivematica/sharedDirectory/currentlyProcessing/mja11-1bf57e5c-21b1-4f9c-b6ee-566f2bf30a27/objects/S0007485312000636/Boreau de Roincé 2013.pdf" "%date%" "%taskUUID%"

Standard streams
Standard error (stderr)

Traceback (most recent call last):
  File "/src/MCPClient/lib/clientScripts/archivematicaClamscan.py", line 114, in <module>
    sys.exit(main(fileUUID, target, date))
  File "/src/MCPClient/lib/clientScripts/archivematicaClamscan.py", line 91, in main
    result = client.scan(target)
  File "/usr/local/lib/python2.7/dist-packages/clamd/__init__.py", line 114, in scan
    return self._file_system_scan('SCAN', file)
  File "/usr/local/lib/python2.7/dist-packages/clamd/__init__.py", line 154, in _file_system_scan
    self._send_command(command, file)
  File "/usr/local/lib/python2.7/dist-packages/clamd/__init__.py", line 229, in _send_command
    concat_args = ' ' + ' '.join(args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 139: ordinal not in range(128)

**Comment by mjaddis** [comment]
Corresponding JIRA issue: https://jiscdev.atlassian.net/browse/RDSSARK-225

**Comment by jrwdunham** [comment]
See https://github.com/artefactual/archivematica/pull/743

**Comment by sevein** [comment]
@jrwdunham fixed this in vanilla via 8d0f495 and I've brought it to our qa/jisc branch: 32486e9.
