### ISSUE TITLE
Problem: file not found error during characterization stage of Transfer workflow

### ISSUE THREAD

**Issue by mjaddis** [JiscRDSS/rdss-archivematica#83]
The 10.1021 dataset (approx 22GB in total) was put through Miguel's new QA env.  The dataset contains tar files.  Extract packages was set to true.  Characterization failed for a file that was extracted from a tar file (10.1021/acs.jctc.5b00728/yildirimmdrnacugdata.tar).  

```
"/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/extractPackagesChoice/miguel_1021-ea973acb-f458-4d21-821e-2cff43c55f84/objects/acs.jctc.5b00728/yildirimmdrnacugdata.tar-2017-10-15T13_58_57.782687_00_00/yildirim_md_rna_cug_data/rCCGCUGCGG_pmf_tor1_tor2/sampling.01.tor1.100.tor2.70.txt.mod.gz" "None" "ea973acb-f458-4d21-821e-2cff43c55f84"


Traceback (most recent call last):
  File "/src/MCPClient/lib/clientScripts/characterizeFile.py", line 101, in <module>
    sys.exit(main(file_path, file_uuid, sip_uuid))
  File "/src/MCPClient/lib/clientScripts/characterizeFile.py", line 58, in main
    file_=file_uuid, sip=sip_uuid, type_='file')
  File "/src/archivematicaCommon/lib/dicts.py", line 54, in replace_string_values
    rd = ReplacementDict.frommodel(**kwargs)
  File "/src/archivematicaCommon/lib/dicts.py", line 99, in frommodel
    file_ = models.File.objects.get(uuid=file_)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
main.models.DoesNotExist: File matching query does not exist.
```

Looking for the file on the underlying file system shows that it does exist:

```
-rw-r--r-- 1 archivematica archivematica 207958 May 13  2015 /mnt/nfs/am-pipeline-data/currentlyProcessing/miguel_1021-d832b088-e00d-483b-9093-e1312f4e49c1/objects/acs.jctc.5b00728/yildirimmdrnacugdata.tar-2017-10-15T13_58_57.782687_00_00/yildirim_md_rna_cug_data/rCCGCUGCGG_pmf_tor1_tor2/sampling.01.tor1.100.tor2.70.txt.mod.gz
```
Note that in the above snippets, the UUID for the error and for the file listing are not the same.  This is because the error was at the Transfer stage so has a transfer UUID but the file listing was done after the dataset had moved to the Ingest stage and hence has an ingest UUID.  However, it does still show that the file existed at the time that the error was thrown (although perhaps the characterisation tool might have been looking in the wrong place or couldn't cope with long filepaths?)

**Comment by mjaddis** [comment]
https://jiscdev.atlassian.net/browse/RDSSARK-283

**Comment by mjaddis** [comment]
The tar file from which the gzip files are extracted is pretty big (over 1GB).  It also looks like there have been several attempts to extract it:
```
archivematica@qa-aws-rdss-archivematica:~/am-pipeline-data/watchedDirectories/workFlowDecisions/selectFormatIDToolIngest/miguel_1021-d832b088-e00d-483b-9093-e1312f4e49c1/objects/acs.jctc.5b00728$ ls -ltr
total 1248488
-rw-r--r-- 1 archivematica archivematica       5383 Oct 13 20:09 10-1021-acs-jctc-5b00728.json
-rw-r--r-- 1 archivematica archivematica          0 Oct 13 20:09 license_rdf
-rw-r--r-- 1 archivematica archivematica 1278443520 Oct 13 20:10 yildirimmdrnacugdata.tar
drwx------ 3 archivematica archivematica         38 Oct 15 10:57 yildirimmdrnacugdata.tar-2017-10-15T10_51_49.324977_00_00
drwx------ 3 archivematica archivematica         38 Oct 15 14:00 yildirimmdrnacugdata.tar-2017-10-15T13_58_57.782687_00_00
drwx------ 3 archivematica archivematica         38 Oct 15 16:10 yildirimmdrnacugdata.tar-2017-10-15T16:09:29.688338+00:00
```

For example:
```
archivematica@qa-aws-rdss-archivematica:~/am-pipeline-data/watchedDirectories/workFlowDecisions/selectFormatIDToolIngest/miguel_1021-d832b088-e00d-483b-9093-e1312f4e49c1/objects/acs.jctc.5b00728$ find . -name sampling.01.tor.0.chi.100.txt.mod.gz
./yildirimmdrnacugdata.tar-2017-10-15T10_51_49.324977_00_00/yildirim_md_rna_cug_data/rCCGCUGCGG_pmf/sampling.01.tor.0.chi.100.txt.mod.gz
./yildirimmdrnacugdata.tar-2017-10-15T13_58_57.782687_00_00/yildirim_md_rna_cug_data/rCCGCUGCGG_pmf/sampling.01.tor.0.chi.100.txt.mod.gz
./yildirimmdrnacugdata.tar-2017-10-15T16:09:29.688338+00:00/yildirim_md_rna_cug_data/rCCGCUGCGG_pmf/sampling.01.tor.0.chi.100.txt.mod.gz
```

**Comment by mjaddis** [comment]
I did another test but this time only put through a subset of 10.1021 that contained the folder with the tar file in it.  It unpacked fine this time.  Same error is thrown by Archivematica.  File exists on the filesystem.

https://archivematica.jisc-qa.archivematica.org/tasks/aa329f41-2d15-4b22-be68-79fc2e06a1d2/

**Comment by mjaddis** [comment]
Also see https://github.com/JiscRDSS/rdss-archivematica/issues/85
