### ISSUE TITLE
Problem: Archivematica workflow stalls at sanitize step for submission documentation

### ISSUE THREAD

**Issue by mjaddis** [JiscRDSS/rdss-archivematica#84]
Two relatively large jobs have both stalled at the 'Sanitize file and directory names in submission documentation' step of the Ingest process.  10.1017 has been like this for 4 days.  10.1021 has been stalled for over 12 hrs.  Smaller jobs complete the process without issue.  

Jobs were run through the new QA env so we have access to all the logs etc. - ask Miguel for access if needed.

![screen shot 2017-10-17 at 07 25 09 2](https://user-images.githubusercontent.com/25819534/31649884-dcfec83a-b30c-11e7-9a0a-41ea29289d2a.png)

**Comment by mjaddis** [comment]
https://jiscdev.atlassian.net/browse/RDSSARK-285

**Comment by mamedin** [comment]
Looking at the MCPServer log file, it seems that the sanitized process ended:
```
INFO      2017-10-13 19:51:20  archivematica.mcp.server:taskStandard:performTask:74:  Executing sanitizeObjectNames_v0.0 {'arguments': '"/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/objects/submissionDocumentation/" "376d8149-07a5-4c56-aa3c-a13137bcc563" "%date%" "%taskUUID%" "SIPDirectory" "sip_id" "/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/"', 'createdDate': '2017-10-13 19:51:20.306181+00:00'}
DEBUG     2017-10-13 19:51:20  archivematica.mcp.server:taskStandard:performTask:93:  Finished performing task 36ddf221-aa4d-4897-b620-fe9e0b70013b
```
But this process failed when writing the big output:
```
(BIG LINE OUTPUT:
DEBUG     2017-10-13 19:51:26  archivematica.mcp.server:taskStandard:check_request_status:98:  Task 23e645af-cebe-4dbf-b738-ceca65eb1ae7 finished! Result COMPLETE - {'stdOut': 'No sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/objects/jfm.2015.492/probedatasub.zip-2017-10-13T17_02_49.899359_00_00/Probe_Data_Sub/Case3/Case10/lower_layer_66_T.txt\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/DIP/objects/76370c05-aadd-40dc-9758-81aeb7949838-10-1017-S1744552312000274.json\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/thumbnails/5727e1f3-27e8-4948-a358-cc5a11249de2.jpg\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/thumbnails/37b96e7a-0f96-4ba2-a4ad-99435b21f63f.jpg\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/DIP/objects/2cce6776-689e-4b64-8238-4e363db5435b-lower_layer_49_T.txt\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/DIP/objects/baeca9e4-5add-45fb-a1f9-c25a59cb01de-modes.dat\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/thumbnails/5316326a-b0d6-4029-95f2-68b27a0f9707.jpg\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/DIP/objects/bab9ac74-97b9-4198-a91f-d140d3c6d1f5-10-1017-S0261444807004909.json\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/objects/jfm.2015.492/probedatasub.zip-2017-10-13T17_02_49.899359_00_00/Probe_Data_Sub/Case1/Case4/lower_layer_2_T.txt\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/thumbnails/d81931ad-72ae-4250-8f61-100f192079bf.jpg\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/DIP/objects/83c2e832-acc4-409c-94af-dcbea454bec7-IsEmpirical.pdf\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/objects/jfm.2015.492/probedatasub.zip-2017-10-13T17_02_49.899359_00_00/Probe_Data_Sub/Case3/Case1/lower_layer_2.txt\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/DIP/objects/226f331f-b8d5-454a-9691-ae2d9d9876c6-lower_layer_59.txt\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/DIP/objects/13b7691d-5871-4b15-b536-ba36ac1875ca-LSD_Psycholog_Med_final.docx\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/thumbnails/155683b1-ad61-4c8e-8c8f-ed4f89b5bcb8.jpg\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/DIP/objects/a40569b8-c224-4dce-a84c-b4d18ecaa3f6-lower_layer_55_T.txt\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/DIP/objects/b496e272-80a8-4a2f-9460-7c9b9c6c8caf-lower_layer_62_T.txt\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/objects/jfm.2015.492/probedatasub.zip-2017-10-13T17_02_49.899359_00_00/Probe_Data_Sub/Case3/Case8/lower_layer_14_T.txt\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/objects/S0260210501005575/10-1017-S0260210501005575.json\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/thumbnails/886f74f0-5f2f-4b75-8361-9b1c7b590a25.jpg\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/objects/jfm.2015.492/probedatasub.zip-2017-10-13T17_02_49.899359_00_00/Probe_Data_Sub/Case1/Case2/lower_layer_7_T.txt\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/thumbnails/3afc99d0-b9dc-4a24-8795-68a1af82018a.jpg\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/objects/jfm.2015.492/probedatasub.zip-2017-10-13T17_02_49.899359_00_00/Probe_Data_Sub/Case3/Case9/lower_layer_44.txt\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/objects/S0033291707000876/10-1017-S0033291707000876.json\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/thumbnails/3e3b4771-0934-43a4-8cf0-57f97fc22d57.jpg\nNo sanitization found for /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/miguel_test_1017-376d8149-07a5-4c56-aa3c-a13137bcc563/objects/jfm.2015.492/probedatasub.zip-2017-10-13T17_02_49.899359_00_00/Probe_Data_Sub/Case3/Case5/lower_layer_31_T.txt\nNo sanitization found for /var/archivematica/shared
...
...
...
)
```
Error:
```
Logging task output to db 23e645af-cebe-4dbf-b738-ceca65eb1ae7
ERROR     2017-10-13 19:51:27  archivematica.mcp.server:utils:wrapped:16:  Uncaught exception
Traceback (most recent call last):
  File "/src/MCPServer/lib/utils.py", line 14, in wrapped
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django_mysqlpool/__init__.py", line 10, in wrapper
    return f(*args, **kwargs)
  File "/src/MCPServer/lib/taskStandard.py", line 91, in performTask
    self.check_request_status(completed_job_request)
  File "/src/MCPServer/lib/taskStandard.py", line 100, in check_request_status
    self.linkTaskManager.taskCompletedCallBackFunction(self)
  File "/src/MCPServer/lib/linkTaskManagerDirectories.py", line 76, in taskCompletedCallBackFunction
    databaseFunctions.logTaskCompletedSQL(task)
  File "/src/archivematicaCommon/lib/databaseFunctions.py", line 250, in logTaskCompletedSQL
    task.save()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 827, in _save_table
    forced_update)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 877, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 580, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1062, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
OperationalError: (1118, 'The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size using innodb_log_file_size.')
Exception in thread Thread-72949:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/src/MCPServer/lib/utils.py", line 14, in wrapped
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django_mysqlpool/__init__.py", line 10, in wrapper
    return f(*args, **kwargs)
  File "/src/MCPServer/lib/taskStandard.py", line 91, in performTask
    self.check_request_status(completed_job_request)
  File "/src/MCPServer/lib/taskStandard.py", line 100, in check_request_status
    self.linkTaskManager.taskCompletedCallBackFunction(self)
  File "/src/MCPServer/lib/linkTaskManagerDirectories.py", line 76, in taskCompletedCallBackFunction
    databaseFunctions.logTaskCompletedSQL(task)
  File "/src/archivematicaCommon/lib/databaseFunctions.py", line 250, in logTaskCompletedSQL
    task.save()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 827, in _save_table
    forced_update)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 877, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 580, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1062, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
OperationalError: (1118, 'The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size using innodb_log_file_size.')
```
It seems that can be fixed increasing the MySQL innodb_log_file_size.

**Comment by mamedin** [comment]
The mysql container log shows the exact values ​​of the blob to be inserted and the redo log:
```
2017-10-13 19:51:27 1 [ERROR] InnoDB: The total blob data length (15088227) is greater than 10% of the total redo log size (100663296). Please increase total redo log size.
```

**Comment by mamedin** [comment]
The innodb_log_file_size has been increased to 2GB. After testing a new 10.1021 transfer, I got the error:
```
File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler\n    raise errorvalue\ndjango.db.utils.OperationalError: (1153, "Got a packet bigger than \'max_allowed_packet\' bytes")\n'}
```
I have increased the MySQL `max_allowed_packet` from 16MB to 64MB and I will run the test again.

**Comment by mamedin** [comment]
After the last change the transfer 10.1021 has successfully completed the sanitize step.

**Comment by sevein** [comment]
@mamedin is going to submit a pull request soon which allows us to customize MySQL configuration directives like `max_allowed_packet`.
